version: "3.7"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/params:/etc/nginx/params
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
