name: Create AWS profile
description: Write AWS credentials file.
inputs:
  profile:
    description: AWS profile name
    required: false
    default: probablefutures
  region:
    description: AWS region
    required: false
    default: us-west-2
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.aws
        cat > ~/.aws/credentials <<EOF
        [${{ inputs.profile }}]
        region=${{ inputs.region }}
        aws_access_key_id=${{ inputs.aws-access-key-id }}
        aws_secret_access_key=${{ inputs.aws-secret-access-key }}
        EOF
