export const requestUserAccessFormFields = [
  {
    id: "fldZEfMzK01lxHhgD",
    name: "Company or organization",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 200,
  },
  {
    id: "fldvs1CXisDQTlHgj",
    name: "Using PF tools for...",
    description: null,
    type: "richText",
    options: null,
    isComputed: false,
    width: 500,
  },
  {
    id: "fldBjdKZSEGbakGLe",
    name: "Email",
    description: null,
    type: "email",
    options: null,
    isComputed: false,
    width: 200,
  },
  {
    id: "fldwJPd59RqClp6dC",
    name: "Email list?",
    description: null,
    type: "singleSelect",
    options: {
      choices: [
        { id: "selWwRMGtAPGpL6MK", name: "Yes, please sign me up.", color: "blueLight2" },
        { id: "selJ3rAbKoJaIpcBC", name: "No, thanks.", color: "cyanLight2" },
      ],
    },
    isComputed: false,
    width: 150,
  },
  {
    id: "fldL30tYRJDTPakaX",
    name: "Anything else?",
    description: null,
    type: "richText",
    options: null,
    isComputed: false,
    width: 150,
  },
  {
    id: "fld7aYwzxiUF3Wqk1",
    name: "Title",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 200,
  },
  {
    id: "fldQfxoR2RzM9C75r",
    name: "Industry",
    description: null,
    type: "multipleRecordLinks",
    options: {
      linkedTableId: "tblsguVwj5yuOHVVO",
      isReversed: false,
      prefersSingleRecordLink: false,
      inverseLinkFieldId: "fldyJJOMUhP4qLD8B",
    },
    isComputed: false,
    width: 100,
  },
  {
    id: "fld2qCQIxJgfU2weL",
    name: "Requested on",
    description: null,
    type: "createdTime",
    options: {
      result: {
        type: "dateTime",
        options: {
          dateFormat: { name: "local", format: "l" },
          timeFormat: { name: "12hour", format: "h:mma" },
          timeZone: "client",
        },
      },
    },
    isComputed: true,
    width: 100,
  },
  {
    id: "fld56lzcRJPV9EDrW",
    name: "What would you like to use?",
    description: null,
    type: "multipleSelects",
    options: {
      choices: [
        { id: "selObrA5VpB4XVjDt", name: "Probable Futures Pro", color: "blueLight2" },
        { id: "selHB9fHgC4AQz2Lj", name: "Probable Futures API", color: "cyanLight2" },
        { id: "selkpsGFYsWDKIm8Z", name: "Probable Futures raw data", color: "tealLight2" },
        {
          id: "sel9Em7tUgvjWQ8fk",
          name: "Probable Futures map tilesets (using Mapbox)",
          color: "greenLight2",
        },
      ],
    },
    isComputed: false,
    width: 400,
  },
  {
    id: "fld86vMpR4WD5sb3e",
    name: "How did you find us?",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 250,
  },
  {
    id: "fldAAYWSbPEk4QRRi",
    name: "Last name",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 200,
  },
  {
    id: "fldUF40ZB8gUYh8iY",
    name: "First name",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 200,
  },
  {
    id: "fldYWWB4mTg5zmbTq",
    name: "Location",
    description: null,
    type: "singleLineText",
    options: null,
    isComputed: false,
    width: 200,
  },
];
