-- This file contains SQL queries to extract various usage statistics from the database and export them as CSV files for analysis.

\copy (SELECT u.email, u.name, COUNT(pp.id) AS project_count, MIN(pp.created_at) AS first_project_created, MAX(pp.created_at) AS last_project_created FROM pf_private.pf_partner_projects pp JOIN pf_private.pf_users u ON pp.partner_id = u.id GROUP BY u.email, u.name ORDER BY project_count DESC) TO '/Users/moustafawehbe/Downloads/pro_total_projects_per_user.csv' WITH CSV HEADER;
\copy (SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS projects_created FROM pf_private.pf_partner_projects GROUP BY month ORDER BY month) TO '/Users/moustafawehbe/Downloads/pro_projects_created_per_month.csv' WITH CSV HEADER;
\copy (SELECT u.email, u.name, COUNT(pdu.id) AS uploads_count, MIN(pdu.created_at) AS first_upload, MAX(pdu.created_at) AS last_upload FROM pf_private.pf_partner_dataset_uploads pdu JOIN pf_private.pf_partner_datasets pd ON pdu.partner_dataset_id = pd.id JOIN pf_private.pf_users u ON pd.partner_id = u.id GROUP BY u.email, u.name ORDER BY uploads_count DESC) TO '/Users/moustafawehbe/Downloads/pro_file_uploads_per_user.csv' WITH CSV HEADER;
\copy (SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS datasets_uploaded FROM pf_private.pf_partner_dataset_uploads GROUP BY month ORDER BY month) TO '/Users/moustafawehbe/Downloads/pro_file_uploads_per_month.csv' WITH CSV HEADER;
\copy (SELECT u.email, u.name, COUNT(pde.id) AS enrichment_count FROM pf_private.pf_partner_dataset_enrichments pde JOIN pf_private.pf_users u ON pde.partner_id = u.id WHERE pde.status = 'successful' GROUP BY u.email, u.name ORDER BY enrichment_count DESC) TO '/Users/moustafawehbe/Downloads/pro_file_enrichments_per_user.csv' WITH CSV HEADER;
\copy (SELECT DATE_TRUNC('month', created_at) AS month, COUNT(*) AS raw_data_downloads FROM pf_private.pf_geo_place_statistics WHERE status = 'successful' GROUP BY month ORDER BY month) TO '/Users/moustafawehbe/Downloads/pro_raw_data_downloads_per_month.csv' WITH CSV HEADER;
\copy (SELECT DATE_TRUNC('month', created_at) AS month, user_sub, action_type, COUNT(*) AS call_count FROM pf_private.pf_audit GROUP BY month, user_sub, action_type ORDER BY month, call_count DESC) TO '/Users/moustafawehbe/Downloads/api_calls_per_user_per_month.csv' WITH CSV HEADER;
\copy (SELECT DATE_TRUNC('month', created_at) AS month, COUNT(DISTINCT user_sub) AS unique_users FROM pf_private.pf_audit GROUP BY month ORDER BY month) TO '/Users/moustafawehbe/Downloads/monthly_active_users.csv' WITH CSV HEADER;
\copy (select d.name as datasetname, u.name as username, du.original_file, d.created_at as uploaded_at from pf_private.pf_partner_datasets d join pf_private.pf_users u on u.id = d.partner_id join pf_private.pf_partner_dataset_uploads du on du.partner_dataset_id = d.id where d.is_example != true and u.name != 'Moustafa Wehbe' order by d.created_at desc) TO '/Users/moustafawehbe/Downloads/pro_datasets_per_user.csv' WITH CSV HEADER;



\copy (WITH project_stats AS ( SELECT  u.id, u.email, u.name, COUNT(pp.id) AS project_count, MIN(pp.created_at) AS first_project_created, MAX(pp.created_at) AS last_project_created FROM pf_private.pf_partner_projects pp JOIN pf_private.pf_users u ON pp.partner_id = u.id GROUP BY u.id, u.email, u.name), upload_stats AS ( SELECT  u.id, COUNT(pdu.id) AS uploads_count, MIN(pdu.created_at) AS first_upload, MAX(pdu.created_at) AS last_upload FROM pf_private.pf_partner_dataset_uploads pdu JOIN pf_private.pf_partner_datasets pd ON pdu.partner_dataset_id = pd.id JOIN pf_private.pf_users u ON pd.partner_id = u.id GROUP BY u.id), enrichment_stats AS ( SELECT  u.id, COUNT(pde.id) AS enrichment_count FROM pf_private.pf_partner_dataset_enrichments pde JOIN pf_private.pf_users u ON pde.partner_id = u.id WHERE pde.status = 'successful' GROUP BY u.id ) SELECT  u.email, u.name, COALESCE(ps.project_count, 0) AS project_count, ps.first_project_created, ps.last_project_created, COALESCE(us.uploads_count, 0) AS uploads_count, us.first_upload, us.last_upload, COALESCE(es.enrichment_count, 0) AS enrichment_count FROM pf_private.pf_users u LEFT JOIN project_stats ps ON u.id = ps.id LEFT JOIN upload_stats us ON u.id = us.id LEFT JOIN enrichment_stats es ON u.id = es.id WHERE  ps.project_count IS NOT NULL OR us.uploads_count IS NOT NULL OR es.enrichment_count IS NOT NULL ORDER BY project_count DESC) TO '/Users/moustafawehbe/Downloads/pro_user_activity_summary.csv' WITH CSV HEADER;
