name: test
on:
  - push
jobs:
  api:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn install --frozen-lockfile
      - run: yarn workspace @probable-futures/api typecheck

  worker:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn install --frozen-lockfile
      - run: yarn workspace @probable-futures/worker typecheck

  maps:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: |
          yarn install --frozen-lockfile
      - run: yarn workspace @probable-futures/maps lint
      - run: yarn workspace @probable-futures/maps test

  prettier:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: |
          yarn install --frozen-lockfile
      - run: yarn format --check
